server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: minio-demo
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true

# MinIO配置
minio:
  endpoint: http://127.0.0.1:9000
  access-key: minioadmin
  secret-key: minioadmin
  bucket-name: default-bucket

# 日志配置
logging:
  level:
    org.feiyue: DEBUG
    io.minio: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  charset:
    console: UTF-8 